### ISSUE TITLE
请问是否考虑在脚本里增加shadowsocks+V2ray plugin这种方式

### ISSUE THREAD

**Issue by oyanli** [h31105/deployX.sh#14]
请问是否考虑在脚本里增加shadowsocks+V2ray plugin这种方式

相对来说，shadowsocks还是比trojan和v2ray的速度来得快，对游戏的支持也最好，大神有没有考虑把shadowsocks+V2ray plugin加入到脚本中，三种协议共享443端口，这样脚本就是最全和最完美的了，希望大神能考虑，感谢大神辛苦付出！！

**Comment by h31105** [comment]
@oyanli 可以考虑…但木有时间表…

**Comment by oyanli** [comment]
谢谢，本来我在毕大的指引下，根据他的脚本有弄好一个ss+trojan+v2ray+caddy的脚本，共享走443端口，但是现在出了trojanGO和vless这样的新协议，毕大这些协议也没有新的教程，总感觉以后的支持会差些，像trojan就很久没更新了，而且我哪个比较简陋，不能一键，只能慢慢输入的，所以还是希望能尽快见到大神的三合一脚本，谢谢！！

**Comment by sportfit** [comment]
ss+v2plugins一点都不好用，敏感期更是如此！论速度trojan-go完全碾压ss，vps线路好坏也是关键，我就用trojan-go玩亚服游戏，非常方便速度很快。
