### ISSUE TITLE
请问 如何和宝塔 共存

### ISSUE THREAD

**Issue by wx-io** [h31105/deployX.sh#19]
请问 如何和宝塔 共存

**Comment by h31105** [comment]
> 请问 如何和宝塔 共存

不太了解宝塔的配置，如果是想解决443端口共用的话，需要手动修改tsp的配置，添加宝塔域名，进行sni分流

例如：
  - name: bt.example.com
    # tlsoffloading: 解开 tls，false 为不解开，直接处理 tls 流量，适用于 trojan-gfw 等
    tlsoffloading: false
    # default: 关闭 tlsoffloading 时，目前没有识别方法，均按其他流量处理
    default:
      handler: proxyPass
    #宝塔端口8443
      args: 127.0.0.1:8443

**Comment by wx-io** [comment]
非常感谢
