### ISSUE TITLE
请教如何安装Dnsmasq

### ISSUE THREAD

**Issue by nichwang88** [h31105/deployX.sh#20]
请问如何在您的v2ray代理中安装dnsmasq，从而实现DNS分流。
我想在您配置的服务器中实现这个脚本，请问是否可以实现，或者手动添加。
https://github.com/steamsv/steamsv.github.io/raw/master/unlock.sh

**Comment by h31105** [comment]
@nichwang88 我简单看了一下，应该是不冲突的，你可以使用unlock.sh脚本自行部署。

**Comment by h31105** [comment]
> 请问如何在您的v2ray代理中安装dnsmasq，从而实现DNS分流。
> 我想在您配置的服务器中实现这个脚本，请问是否可以实现，或者手动添加。
> https://github.com/steamsv/steamsv.github.io/raw/master/unlock.sh

另外补充，使用unlock.sh脚本 **在宿主机** 部署dns分流（netflix解锁）后，理论上此节点的所有代理服务（trojan-go、v2ray）都会被分流。（dns解锁部署完成后，重启代理容器再做确认

**Comment by nichwang88** [comment]
难倒我了，没搞定，我安装了dnsmasq脚本以后没能实现解锁功能。
无奈用回了原来的一键脚本v2ray，再使用该脚本能实现解锁，这个问题暂时就这样吧，超出了我能解决的范围。

**Comment by h31105** [comment]
这个问题的原因找到了。。[详情点这里](https://github.com/moby/moby/issues/23910)
docker 容器默认情况下会套用host主机的/etc/resolv.conf dns设置，**但会忽略 localhost dnsserver（127.0.0.1）而使用google dns 8.8.8.8**
我建议你手动指定 docker 容器的dns地址试试，比如：
docker run -d --network host **--dns 127.0.0.1** --name Trojan-Go --restart=always -v /etc/trojan-go:/etc/trojan-go teddysun/trojan-go
