### ISSUE TITLE
nat 部署问题

### ISSUE THREAD

**Issue by happy201807** [h31105/deployX.sh#21]
您好，请问通过前置nginx反代ws共享443端口的nat安装时无法自动获取证书，该把通过其他vps申请的证书放到哪个文件夹？

**Comment by h31105** [comment]
> 您好，请问通过前置nginx反代ws共享443端口的nat安装时无法自动获取证书，该把通过其他vps申请的证书放到哪个文件夹？

落地 tsp 前置分流？
把证书cert和key文件放在tsp证书目录：
/etc/ssl/tls-shunt-proxy/certificates/acme-v02.api.letsencrypt.org-directory/<域名> （可能需要手动创建）目录下试试
**P.S 请注意保持该目录以及证书文件的tls-shunt-proxy用户读取权限**

**Comment by h31105** [comment]
emmm..忍不住还是要多说一句，NAT机 若非必要，还是建议部署的越简单越好（比如，直接部署裸ws，再套cloudflare），毕竟出口IP是共用的，IP安全不是某一个人能够决定的。

**Comment by happy201807** [comment]
您说的很对，nat只要装trojan go ws就够了，证书和nginx通过面板部署在前置的母鸡上，可是单纯'trojan go ws'这个通过脚本可以完成吗？要怎么安装？

**Comment by h31105** [comment]
> 您说的很对，nat只要装trojan go ws就够了，证书和nginx通过面板部署在前置的母鸡上，可是单纯'trojan go ws'这个通过脚本可以完成吗？要怎么安装？

没写...
不过你可以在用脚本部署完trojan-go ws后，把tsp卸载或停用，然后手动修改trojan-go config 文件（改完重启 docker restart Trojan-Go）中监听地址的部分：127.0.0.1 -> 0.0.0.0 这样nat机就是trojan-go的裸ws

**Comment by happy201807** [comment]
OK thanks.
