### ISSUE TITLE
V2Ray TCP 模式是否需要修改为 Domain Socket

### ISSUE THREAD

**Issue by GossipRanR** [h31105/deployX.sh#24]
根据官方白话文文档中描述 https://guide.v2fly.org/advanced/tcp_tls_shunt_proxy.html#domain-socket
使用v2ray+tcp模式时在TLS分流器和v2ray服务端之间使用 Domain Socket 会有较明显的性能差距。
请问是否需要优化此安装脚本或是此种设置没必要？

**Comment by h31105** [comment]
> 根据官方白话文文档中描述 https://guide.v2fly.org/advanced/tcp_tls_shunt_proxy.html#domain-socket
> 使用v2ray+tcp模式时在TLS分流器和v2ray服务端之间使用 Domain Socket 会有较明显的性能差距。
> 请问是否需要优化此安装脚本或是此种设置没必要？

这个所谓的性能提升，我没有实际验证过，你可以试试，如果可以的话，顺便告诉我测试结果，谢谢。
