### ISSUE TITLE
关于trojan-go的配置文件

### ISSUE THREAD

**Issue by GossipRanR** [h31105/deployX.sh#25]
您好。我通读了这个安装脚本，发现Trojan-Go的配置文件中的第一层级出现了"fallback_addr"和"fallback_port"的key（如图）。
![image](https://user-images.githubusercontent.com/59172555/106690916-924c1600-660d-11eb-85c0-ed8c3d1a40e1.png)
在Trojan-Go的官方文档的[完整的配置文件](https://p4gefau1t.github.io/trojan-go/basic/full-config/)一节中，这两个key出现在了第二层级中，也就是"ssl"之下，如图
![image](https://user-images.githubusercontent.com/59172555/106691313-40f05680-660e-11eb-9b1b-b48fd71d883a.png)
请问这样的配置是否正确，是因为tsp对tls解密之后才需要这样的配置吗（我知道tsp到trojan-go已经没有了ssl的加密），这样的配置是否生效了呢？
谢谢

**Comment by h31105** [comment]
> 您好。我通读了这个安装脚本，发现Trojan-Go的配置文件中的第一层级出现了"fallback_addr"和"fallback_port"的key（如图）。
> ![image](https://user-images.githubusercontent.com/59172555/106690916-924c1600-660d-11eb-85c0-ed8c3d1a40e1.png)
> 在Trojan-Go的官方文档的[完整的配置文件](https://p4gefau1t.github.io/trojan-go/basic/full-config/)一节中，这两个key出现在了第二层级中，也就是"ssl"之下，如图
> ![image](https://user-images.githubusercontent.com/59172555/106691313-40f05680-660e-11eb-9b1b-b48fd71d883a.png)
> 请问这样的配置是否正确，是因为tsp对tls解密之后才需要这样的配置吗（我知道tsp到trojan-go已经没有了ssl的加密），这样的配置是否生效了呢？
> 谢谢

当前脚本的部署 trojan-go 是通过tsp的trojan特征分流，所以trojan-go配置中的 remote&fallback_address其实是不起作用的（所有http请求已经被前置的tsp 拦截分流）

**Comment by liberal-boy** [comment]
@h31105 请注意，分流器只能分辨"这是 trojan 协议"，不能确定"这个 trojan 请求能否认证成功"，所以我认为 trojan-go 的 fallback 还是需要的，可以直接 fallback 到分流器的 redirect 端口上（反正肯定是非法的 http 请求，fallback 到任意 http handler 上都可以）

**Comment by GossipRanR** [comment]
我提问此问题的核心是想说 fallback 的相关字段的层级问题。我想提问的有两个地方
1、官方给出的配置文档 fallback相关字段是在ssl下的，也就是ssl.fallback_port。但是本脚本中对fallback的配置是在json顶层的，也就是不处于ssl的key之下。我不知道这样的配置会不会生效
2、ssl也就是tls已经在tsp中被解密了，从tsp到trojan-go已经没有ssl了，那ssl字段是否还被程序读取，即使层级正确了trojan-go的程序是否还认该参数。

**Comment by h31105** [comment]
> 我提问此问题的核心是想说 fallback 的相关字段的层级问题。我想提问的有两个地方
> 1、官方给出的配置文档 fallback相关字段是在ssl下的，也就是ssl.fallback_port。但是本脚本中对fallback的配置是在json顶层的，也就是不处于ssl的key之下。我不知道这样的配置会不会生效
> 2、ssl也就是tls已经在tsp中被解密了，从tsp到trojan-go已经没有ssl了，那ssl字段是否还被程序读取，即使层级正确了trojan-go的程序是否还认该参数。

我印象中，fallback&remote字段在trojan-go之前的的版本中都是在第一级的，现在0.82版本如果移入ssl子项的话，应该意味着tls前置的情况下，fallback可能就无效了

**Comment by h31105** [comment]
> @h31105 请注意，分流器只能分辨"这是 trojan 协议"，不能确定"这个 trojan 请求能否认证成功"，所以我认为 trojan-go 的 fallback 还是需要的，可以直接 fallback 到分流器的 redirect 端口上（反正肯定是非法的 http 请求，fallback 到任意 http handler 上都可以）

据我之前的测试，如果需要完整实现trojan-go的fallback&remote转发，需要使用tsp的 default 分流，（当前脚本的default分流留给了v2ray-core），不过我个人觉得 这不是啥大问题。

**Comment by liberal-boy** [comment]
> > @h31105 请注意，分流器只能分辨"这是 trojan 协议"，不能确定"这个 trojan 请求能否认证成功"，所以我认为 trojan-go 的 fallback 还是需要的，可以直接 fallback 到分流器的 redirect 端口上（反正肯定是非法的 http 请求，fallback 到任意 http handler 上都可以）
> 
> 据我之前的测试，如果需要完整实现trojan-go的fallback&remote转发，需要使用tsp的 default 分流，（当前脚本的default分流留给了v2ray-core），不过我个人觉得 这不是啥大问题。

不设置 fallback 的情况下，使用伪造的 trojan 请求是有可能发现特性的。

**Comment by GossipRanR** [comment]
> > > @h31105 请注意，分流器只能分辨"这是 trojan 协议"，不能确定"这个 trojan 请求能否认证成功"，所以我认为 trojan-go 的 fallback 还是需要的，可以直接 fallback 到分流器的 redirect 端口上（反正肯定是非法的 http 请求，fallback 到任意 http handler 上都可以）
> > 
> > 
> > 据我之前的测试，如果需要完整实现trojan-go的fallback&remote转发，需要使用tsp的 default 分流，（当前脚本的default分流留给了v2ray-core），不过我个人觉得 这不是啥大问题。
> 
> 不设置 fallback 的情况下，使用伪造的 trojan 请求是有可能发现特性的。

所以很尴尬 如果按这样的配置来看 最新的trojan-go应该是不识别的
我又看了下trojan-gfw和trojan-go的官方文档，其中trojan-gfw没有对fallback的描述，而trojan-go中fallback的两个相关配置项确实是出现在ssl层级下了。所以需要大佬们确认一下。非常感谢

**Comment by GossipRanR** [comment]
由于tsp的方案对cdn不太友好，而某些注意是不能随意更换ip的（锁ip）。所以我要确信把风险降到最低。

**Comment by h31105** [comment]
> > > @h31105 请注意，分流器只能分辨"这是 trojan 协议"，不能确定"这个 trojan 请求能否认证成功"，所以我认为 trojan-go 的 fallback 还是需要的，可以直接 fallback 到分流器的 redirect 端口上（反正肯定是非法的 http 请求，fallback 到任意 http handler 上都可以）
> > 
> > 
> > 据我之前的测试，如果需要完整实现trojan-go的fallback&remote转发，需要使用tsp的 default 分流，（当前脚本的default分流留给了v2ray-core），不过我个人觉得 这不是啥大问题。
> 
> 不设置 fallback 的情况下，使用伪造的 trojan 请求是有可能发现特性的。

配置我是保留了，但根据trojan-go的文档描述，fallback在tls前置的情况下，很可能无效

> fallback_addr和fallback_port指服务端TLS握手失败时，trojan-go将该连接重定向到该地址。这是trojan-go的特性，以便更好地隐蔽服务器，抵抗GFW的主动检测，使得服务器的443端口在遭遇非TLS协议的探测时，行为与正常服务器完全一致。当服务器接受了一个连接但无法进行TLS握手时，如果fallback_port不为空，则流量将会被代理至fallback_addr:fallback_port。如果fallback_addr为空，则用remote_addr填充。例如，你可以在本地使用nginx开启一个https服务，当你的服务器443端口被非TLS协议请求时（比如http请求），trojan-go将代理至本地https服务器，nginx将使用http协议明文返回一个400 Bad Request页面。你可以通过使用浏览器访问http://your-domain-name.com:443进行验证。

**Comment by liberal-boy** [comment]
> 由于tsp的方案对cdn不太友好，而某些注意是不能随意更换ip的（锁ip）。所以我要确信把风险降到最低。

tsp 是支持 wss path 分流的。

**Comment by h31105** [comment]
> 由于tsp的方案对cdn不太友好，而某些注意是不能随意更换ip的（锁ip）。所以我要确信把风险降到最低。

tsp是sni转发，cdn是没问题的，只需要注意SNI设置就可以了

**Comment by GossipRanR** [comment]
我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐

**Comment by h31105** [comment]
> 我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐

其实大可不必这么紧张，trojan-gfw、ss、vmess都没有fallback不也是好好的么。
我这里自用部署的10个节点，最长的已经快一年了，一直没有问题。

**Comment by liberal-boy** [comment]
感觉 trojan-go 对 fallback_port 的描述怪怪的，可能要给他提个 issue 问问。

**Comment by GossipRanR** [comment]
> > 我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐
> 
> 其实大可不必这么紧张，trojan-gfw、ss、vmess都没有fallback不也是好好的么。
> 我这里自用部署的10个节点，最长的已经快一年了，一直没有问题。

安全是一个方面 最主要的还是想对这些东西有一个了解

**Comment by h31105** [comment]
> > > 我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐
> > 
> > 
> > 其实大可不必这么紧张，trojan-gfw、ss、vmess都没有fallback不也是好好的么。
> > 我这里自用部署的10个节点，最长的已经快一年了，一直没有问题。
> 
> 安全是一个方面 最主要的还是想对这些东西有一个了解

从目前的信息来看，如果想完整实现fallback就不能tls前置（包括xray/v2ray的 vless fallback 我想应该也是一样）

**Comment by liberal-boy** [comment]
> > > > 我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐
> > > 
> > > 
> > > 其实大可不必这么紧张，trojan-gfw、ss、vmess都没有fallback不也是好好的么。
> > > 我这里自用部署的10个节点，最长的已经快一年了，一直没有问题。
> > 
> > 
> > 安全是一个方面 最主要的还是想对这些东西有一个了解
> 
> 从目前的信息来看，如果想完整实现fallback就不能tls前置（包括xray/v2ray的 vless fallback 我想应该也是一样）

v2ray 的 trojan 以及 vless 的 fallback 与 tls 无关。

**Comment by h31105** [comment]
> > > > > 我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐
> > > > 
> > > > 
> > > > 其实大可不必这么紧张，trojan-gfw、ss、vmess都没有fallback不也是好好的么。
> > > > 我这里自用部署的10个节点，最长的已经快一年了，一直没有问题。
> > > 
> > > 
> > > 安全是一个方面 最主要的还是想对这些东西有一个了解
> > 
> > 
> > 从目前的信息来看，如果想完整实现fallback就不能tls前置（包括xray/v2ray的 vless fallback 我想应该也是一样）
> 
> v2ray 的 trojan 以及 vless 的 fallback 与 tls 无关。

但v2fly的配置文档指出
“**fallbacks 项是可选的，只能用于 TCP+TLS 传输组合**”
“**注意：fallbacks 所在入站本身必须是 TCP+TLS，这是分流至其它 WS 入站用的，被分流的入站则无需配置 TLS。**”
https://www.v2fly.org/config/protocols/vless.html#fallbackobject

**Comment by liberal-boy** [comment]
> > > > > > 我是说 fallback的问题 最好能确认并修复一下 必经这样多少还是增加了风险 我是不想ip被和谐
> > > > > 
> > > > > 
> > > > > 其实大可不必这么紧张，trojan-gfw、ss、vmess都没有fallback不也是好好的么。
> > > > > 我这里自用部署的10个节点，最长的已经快一年了，一直没有问题。
> > > > 
> > > > 
> > > > 安全是一个方面 最主要的还是想对这些东西有一个了解
> > > 
> > > 
> > > 从目前的信息来看，如果想完整实现fallback就不能tls前置（包括xray/v2ray的 vless fallback 我想应该也是一样）
> > 
> > 
> > v2ray 的 trojan 以及 vless 的 fallback 与 tls 无关。
> 
> 但v2fly的配置文档指出
> “**fallbacks 项是可选的，只能用于 TCP+TLS 传输组合**”
> “**注意：fallbacks 所在入站本身必须是 TCP+TLS，这是分流至其它 WS 入站用的，被分流的入站则无需配置 TLS。**”
> https://www.v2fly.org/config/protocols/vless.html#fallbackobject

vless 没仔细看，trojan 没这个要求，尽管 v2ray 的trojan 回落也没有认证。但很明显，认证回落并不依赖 tls，这是两个层上的事情，没有什么关联。实际上 vless 协议本身的回落也可不依赖 tls，只是他设计了 alpn 分流导致与 tls 有一定耦合了。
